# "Deploy" to an environment
name: Dummy workflow to simulate deploying to an environment

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency: 
  # limit concurrency to the workflow level
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy-CI:
    name: Deploy-CI
    runs-on: ubuntu-latest
    environment: CI

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: deploy
      run: |
        echo "deploying to environment... "
        cat infrastructure/deployment.txt

    - name: verify
      run: |
        echo "running post deployment checks..."
  deploy-nonprod:
    name: Deploy-NonProd
    runs-on: ubuntu-latest
    environment: nonprod
    needs: deploy-CI

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: deploy
      run: |
        echo "deploying to environment... "
        cat infrastructure/deployment.txt

    - name: verify
      run: |
        echo "running post deployment checks..."
  deploy-production:
    name: Deploy-Production
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-nonprod

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: deploy
      run: |
        echo "deploying to environment... "
        cat infrastructure/deployment.txt

    - name: verify
      run: |
        echo "running post deployment checks..."
        echo "post deployment checks failed"
